apiVersion: batch/v1
kind: Job
metadata:
  name: terra-runner
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 6000

  template:
    spec:
      serviceAccountName: terra
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: amd64

      containers:
        - name: terra-runner
          image: terra-test
          volumeMounts:
            - name: apps
              mountPath: /apps

      volumes:
        - name: apps
          hostPath:
            path: /apps
            type: Directory
