apiVersion: v1
kind: PersistentVolume
metadata:
  name: terra-test-data
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /apps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terra-test-claim
spec:
  storageClassName: local-storage
  volumeName: terra-test-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
