kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./
        containerPath: /repo
      - hostPath: ./.apps/data/
        containerPath: /apps/data/
      - hostPath: ./.apps/installs/
        containerPath: /apps/installs/
    labels:
      juno-innovations.com/service: "true"
