kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30080
      hostPort: 8080
      protocol: TCP
    - containerPort: 30088
      hostPort: 8888
      protocol: TCP
    extraMounts:
      - hostPath: ./
        containerPath: /repo
      - hostPath: ./.apps/data/
        containerPath: /apps/data/
      - hostPath: ./.apps/installs/
        containerPath: /apps/installs/
    labels:
      juno-innovations.com/service: "true"
