apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows
spec:
  volumeName: windows
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi