apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: terra

build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: terra-test
      docker:
        dockerfile: Dockerfile
        target: test
        buildArgs:
          TARGET: "{{ .TARGET }}"

verify:
  # run integration tests
  - name: terra-test
    timeout: 600
    container:
      image: terra-test
      name: terra-test
    # target run for in the cluster
    executionMode:
      kubernetesCluster:
        jobManifestPath: tests/test_runner.yaml

manifests:
  rawYaml:
    - k8s/*

