apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/apps/installs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-pv-claim
spec:
  volumeName: apps-pv-volume
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
