---
apiVersion: v1
kind: Service
metadata:
  name: deadline-server
spec:
  selector:
    app: deadline-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: endpoint
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: rest
---
apiVersion: v1
kind: Service
metadata:
  name: deadline-mongo
spec:
  selector:
    app: deadline-mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: db-port

