name: Delete old workflow runs
on:
  push:
    paths:
      - '.github/workflows/run-cleanup.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  del_runs:
    runs-on:
      - self-hosted
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.JUNO_CI_APP_ID }}
          private-key: ${{ secrets.JUNO_CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 6
