name: Verify Packages

on:
  push:

jobs:
  verify:
    runs-on:
      - X64
    container:
      image: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify packages
        run: |
          pwd
          ls -la
          bash hack/verify.sh
