name: Verify Packages

on:
  push:

jobs:
  verify:
    runs-on:
      - X64
    container:
      image: ubuntu
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify packages
        run: make verify
