name: Verify Packages

on:
  push:
    paths:
      - plugins/**

jobs:
  verify:
    runs-on:
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: 'true'
      - name: Verify packages
        run: make verify
