name: Verify Linting

on:
  push:
    paths:
      - plugins/**

jobs:
  linting:
    runs-on:
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: 'true'
      - name: Verify linting
        run: make lint
