name: Verify Packages

on:
  push:

jobs:
  verify:
    runs-on:
      - X64  # Your custom self-hosted runner label
    container:
      image: ubuntu:22.04
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl make git tar gzip
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify packages
        run: |
          ls -la plugins/*/templates/
          make verify
